version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: carservice_postgres
    environment:
      POSTGRES_DB: carservice_db
      POSTGRES_USER: carservice_user
      POSTGRES_PASSWORD: carservice_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: carservice_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@carservice.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data: 
  pgadmin-data:   